USE proyecto0006;

INSERT INTO docentes (codigoInstitucion, nombreIES, generoDocente, tipoDocumento, nivelFormacion, tiempoDedicacion, tipoContrato, departamento, municipio, conteo2013) VALUES
('1101','UNIVERSIDAD NACIONAL DE COLOMBIA','FEMENINO','EXTRANJERO','DOCTORADO','CATEDRA','TERMINO INDEFINIDO','BOGOTA D.C.','BOGOTA D.C.',2),
('1101','UNIVERSIDAD NACIONAL DE COLOMBIA','FEMENINO','NACIONAL','TECNICO PROFESIONAL','CATEDRA','TERMINO FIJO','BOGOTA D.C.','BOGOTA D.C.',0),
('1101','UNIVERSIDAD NACIONAL DE COLOMBIA','MASCULINO','EXTRANJERO','DOCTORADO','CATEDRA','TERMINO FIJO','BOGOTA D.C.','BOGOTA D.C.',3),
('1101','UNIVERSIDAD NACIONAL DE COLOMBIA','MASCULINO','NACIONAL','TECNICO PROFESIONAL','CATEDRA','TERMINO FIJO','BOGOTA D.C.','BOGOTA D.C.',0),
('1102','UNIVERSIDAD NACIONAL DE COLOMBIA','FEMENINO','EXTRANJERO','DOCTORADO','TIEMPO COMPLETO','TERMINO INDEFINIDO','ANTIOQUIA','MEDELLIN',6);
